rubyonrails/members-only/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :posts

  root "posts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rubyonrails/members-only/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

rubyonrails/members-only/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

rubyonrails/members-only/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action only: [:new, :create, :index]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.fetch(:post, {}).permit(:body)
    end
end

rubyonrails/members-only/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end 
end

rubyonrails/members-only/app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :body,
        label: "Tweet about it",
        input_html: { class: "textarea" },
        wrapper: false,
        label_html: { class: "label" },
        placeholder: "Compose a new tweeet...",
        autofocus: true
    %>
  </div>
</div>
<%= f.button :submit, class: "button is-info" %>
<% end %>

rubyonrails/members-only/app/views/posts/_make_post.html.erb
<%= form_with model: @post do |f| %>
  <div class="relative grid grid-cols-1 gap-4 p-4 mb-8 border rounded-lg bg-white shadow-lg">
    <div class="relative flex gap-4">
        <div class="flex flex-col w-full">
            <div class="w-full md:w-full mb-2 mt-2">
              <%= f.text_area :body,
                required: true,
                autofocus: true,
                class: "bg-gray-100 rounded border border-gray-400 leading-normal resize-none w-full h-20 py-2 px-3 font-medium placeholder-gray-700 focus:outline-none focus:bg-white",
                placeholder: 'What are you thinking?'
              %>
           </div>
          <%= f.button new_user_session_path, class: "mt-5 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
            Publish
          <% end %>
        </div>
    </div>
  </div>
<% end %>

rubyonrails/members-only/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <% if action_name != "show" %>
    <%= link_to "Show this post", post, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this post', edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

rubyonrails/members-only/app/views/posts/_posts.html.erb
<div>
  <% @posts.each do | post | %>
    <div class="relative grid grid-cols-1 gap-4 p-4 mb-8 border rounded-lg bg-white shadow-lg">
      <div class="relative flex gap-4">
          <img src="https://icons.iconarchive.com/icons/diversity-avatars/avatars/256/charlie-chaplin-icon.png" class="relative rounded-lg -top-8 -mb-4 bg-white border h-20 w-20" alt="" loading="lazy">
          <div class="flex flex-col w-full">
              <div class="flex flex-row justify-between">
                <% if user_signed_in? %>              
                  <p class="relative text-xl whitespace-nowrap truncate overflow-hidden"><%= current_user.username %></p>
                <% else %>
                  <p class="relative text-xl whitespace-nowrap truncate overflow-hidden">Anonymous</p>
                <% end %>
              </div>
              <p class="text-gray-400 text-sm">20 April 2022, at 14:88 PM</p>
          </div>
      </div>
      <p class="-mt-4 text-gray-500"><%= post.body %></p>
    </div>
  <% end %>
</div>

rubyonrails/members-only/app/views/posts/_trends.html.erb
<div class="bg-white w-96 place-self-start">
  <div class="font-semibold">
    Recommended Topics
  </div>
  
  <div class="mt-3 flex flex-wrap gap-3">
    <button class="bg-gray-200 hover:bg-gray-300 duration-300 rounded-full px-4 py-2 font-light text-sm">
      Music
    </button>
    <button class="bg-gray-200 hover:bg-gray-300 duration-300 rounded-full px-4 py-2 font-light text-sm">
      Ux
    </button>
    <button class="bg-gray-200 hover:bg-gray-300 duration-300 rounded-full px-4 py-2 font-light text-sm">
      Strategy
    </button>
    <button class="bg-gray-200 hover:bg-gray-300 duration-300 rounded-full px-4 py-2 font-light text-sm">
      Makers
    </button>
    <button class="bg-gray-200 hover:bg-gray-300 duration-300 rounded-full px-4 py-2 font-light text-sm">
      Time Series Analysis
    </button>
    <button class="bg-gray-200 hover:bg-gray-300 duration-300 rounded-full px-4 py-2 font-light text-sm">
      Gaming
    </button>
    <button class="bg-gray-200 hover:bg-gray-300 duration-300 rounded-full px-4 py-2 font-light text-sm">
      Fintech
    </button>   
  </div>
</div>
  

rubyonrails/members-only/app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Show this post", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to posts", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

rubyonrails/members-only/app/views/posts/index.html.erb
<div>
  <div class="w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block justify-center" id="notice"><%= notice %></p>
    <% end %>
  
    <div class="flex justify-center items-center">
      <h1 class="font-bold text-4xl mt-6">News</h1>
    </div>
  
    <div class="grid grid-cols-2 gap-2 content-center mt-20 place-items-center">
      <div class="w-full flex flex-col justify-center align-items-end">
        <% if user_signed_in? %>
          <%= render "make_post" %>
        <% end %>
        <%= render "posts" %>
      </div>
      <div class="w-full place-self-start flex justify-center">
        <%= render "trends" %>
      </div>
    </div>
  </div>
</div>

rubyonrails/members-only/app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New post</h1>

  <%= render "form", post: @post %>

  <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

rubyonrails/members-only/app/views/posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block justify-center" id="notice"><%= notice %></p>
    <% end %>

    <%= render @post %>

    <%= link_to 'Edit this post', edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this post', post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to posts', posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

rubyonrails/members-only/app/views/users/shared/_links.html.erb
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>